### ISSUE TITLE
Shadows

### ISSUE THREAD

**Issue by kamsebgoralski** [akaimo/LNFloatingActionButton#3]
Can you add to class LNFloatingActionButton set shadowColor and to LNFloatingActionButtonTitleCell shadow options?

**Comment by akaimo** [comment]
Hi, @kamsebgoralski 

Yes. I will add shadowColor immediately.
However, adding shadow options to LNFloatingActionButtonTitleCell requires a little development, so please wait for a while.

**Comment by kamsebgoralski** [comment]
Thanks so much @akaimo

**Comment by akaimo** [comment]
Sorry to be late.
I supported cell shadow options in v0.2.0.
Please try using it by all means.
